export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const SUBMITTING = "SUBMITTING";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SIGNUP_LOADING = "SIGNUP_LOADING";
export const GET_LANG_SUCCESS = "GET_LANG_SUCCESS";
export const GET_LANG_FAILED = "GET_LANG_FAILED";
export const GET_LANG_LOADING = "GET_LANG_LOADING";
export const LANG_TO_LEARN = "LANG_TO_LEARN";
export const PROFICIENCY = "PROFICIENCY";
export const LANG_SUCCESS = "LANG_SUCCESS";
export const LANG_FAILED = "LANG_FAILED";
export const SPOKEN_LANG = "SPOKEN_LANG";
export const CLEAR_LOGIN_MSG = "CLEAR_LOGIN_MSG";
